### PR TITLE
added example game-gonu.tb

### PR DESCRIPTION
**Pull request by vaibhavdaren**
ported sample example from turtleart to turtleblockjs
Give feedback if any changes needed.

### CODE REVIEW

**Comment by walterbender** [comment]
A few problems with this project:
(1) add turtle is not available in the JS version of turtle. Individual start blocks could be used instead.
(2) the do --> action name blocks should be replaced by action-name blocks
(3) please use the home button to align all of the stacks

**Comment by vaibhavdaren** [comment]
understood :+1: 
I  will make the required changes. Thank you for the explanation.

**Comment by walterbender** [comment]
See https://musicblocks.sugarlabs.org/index.html?id=1525021229213735&run=True
I added support for clicking the pieces to move them to the open position.

**Comment by walterbender** [comment]
FWIW, I just added some new blocks: set turtle and found turtle. Used along with make block, you can do something along the lines of:
https://github.com/sugarlabs/turtleart-activity/blob/master/samples/graphics-turtles.ta

See https://turtle.sugarlabs.org/index.html?id=1525196995361206&run=True

All of this has me thinking we may want to also add a new turtle block that encapsulates the above as per the Python version.

**Comment by walterbender** [comment]
https://musicblocks.sugarlabs.org/index.html?id=1525211505767290&run=True uses the "new turtle" block.

**Pull request closed without merging**
