### PR TITLE
changes made in palette and toolbar.js

### PR DESCRIPTION
**Pull request by Harshdev098**
## fixes
1. fixed the problem of not displaying the title of `set pitch preview` on hover to its icon in the toolbar
2. fixed the cursor pointer property which is displaying on all the options of the palette except on the search option

### CODE REVIEW

**Review by Ajay-singh1 — APPROVED** [review]
LGTM! Wait for final approval.

**Comment by walterbender** [comment]
What exactly is the current problem with the palette cursor? You change will make it so that the rollover behavior for the search will **not** be a text cursor. Why is that desirable?

Also, there seems to already be a preview for set pitch preview. Are you not seeing it?

**Comment by Harshdev098** [comment]
@walterbender   yes sir, I can't see the preview for set pitch preview that's why I have changed the toolbar.js file and I have seen this problem in both advanced mode and beginner mode
and changing the cursor behaviour is my personal opinion because the search bar opens when we click it, and it not seems good with text cursor

Screenshot 2023-11-08 181024

**Comment by Ajay-singh1** [comment]
@Harshdev098 I think the rollover behavior is just fine you not need to change it. @walterbender What are your views on the set pitch preview?.

**Comment by Ajay-singh1** [comment]
@Harshdev098 You don't need to change the behavior of search it looks fine. @walterbender Their is some issue with the set pitch preview  it is not showing on the website.

**Review by Ajay-singh1 — CHANGES_REQUESTED** [review]
Leave the code as it is! The set pitch preview is fine.

**Comment by walterbender** [comment]
What OS/Browser are you using when the Set Preview Pitch hover message is not appearing? It works fine with Fedora/Firefox.

Screenshot from 2023-11-08 15-00-01

I prefer the text cursor because it lets the user know that they will be typing.

**Comment by Ajay-singh1** [comment]
@walterbender I have checked on chrome and it is not showing up their.

**Comment by Harshdev098** [comment]
yeah, its not showing in both chrome and microsoft edge

**Comment by walterbender** [comment]
Screenshot from 2023-11-09 10-37-54
Chrome ^^ (on Fedora)

**Comment by walterbender** [comment]
Also, FWIW, this MR add the hover help to the Turtle Blocks code where that menu item is not used. It is already in the Music Blocks code.

**Comment by Harshdev098** [comment]
Thanks for the info,I'm happy to make any changes or concerns you may have.
Also, I'am eager to contribute to this organization can you please assign or suggest some good first issue to kick start with impactful contributions

**Comment by Ajay-singh1** [comment]
@Harshdev098 We can Close this MR Now.

**Comment by Ajay-singh1** [comment]
@walterbender Can we close this PR now?

**Pull request closed without merging**
