### PR TITLE
Added Interactive Exercises for TurtleBlocks

### PR DESCRIPTION
**Pull request by vaibhavdaren**
Added checkpoint based exercises for TurtleblockJS.
main Pull Request GSOC18.

### CODE REVIEW

**Comment by vaibhavdaren** [comment]
@jaskirat2000 thankyou  :)

**Comment by Ramaraju-1996** [comment]
Great work @vaibhavdaren :) 
Hope you had a great GSOC experience!

**Comment by geekrypter** [comment]
Great work @vaibhavdaren :)
Hope you had a great GSOC experience!

**Comment by walterbender** [comment]
Would be great to put relevant text into the alt-tags for all of the images.

**Comment by vaibhavdaren** [comment]
@walterbender  done in patch #443

**Pull request merged**
